(function(g){var window=this;var L6=function(a,b){return g.aa[a]=b},Nva=function(a,b){var c=new g.EI;
c.o=a.o;c.D=a.D;c.C=a.C;c.B=a.B;c.G=a.G;c.F=a.F;c.J=a.J;c.g=b;return c},M6=function(a){return a.g?a.g.languageCode:a.o},N6=function(a){var b={format:a.A,
languageCode:a.o,languageName:a.D,displayName:g.FI(a),kind:a.B,name:a.C,id:a.Ca,is_servable:a.O,is_translateable:a.G,vss_id:a.F};a.g&&(a=a.g,b.translationLanguage={languageCode:a.languageCode,languageName:a.languageName,languageOriginal:a.g,id:a.id,is_default:a.isDefault});return b},O6=function(a){if(!Ova.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(Pva,"#$1$1$2$2$3$3"));a=a.toLowerCase();return[(0,window.parseInt)(a.substr(1,2),16),(0,window.parseInt)(a.substr(3,2),16),(0,window.parseInt)(a.substr(5,2),16)]},Qva=function(a,b){for(var c in a)if(!(c in b)||a[c]!==b[c])return!1;
for(c in b)if(!(c in a))return!1;return!0},Rva=function(a){for(var b in a)delete a[b]},P6=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.EJ.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.C=f;this.o=k},Q6=function(a,b,c,d,e){g.EJ.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.o=[]},S6=function(a){a=void 0===a?{}:a;
var b="_"+R6++;return new Q6(0,0x8000000000000,0,b,a)},V6=function(a,b,c,d,e,f){var k={};
g.Aa(k,b);g.Aa(k,a.params);g.Aa(k,c);var l={};g.Aa(l,b.sb);a.params.sb&&g.Aa(l,a.params.sb);g.Aa(l,c.sb);k.sb=l;g.X.call(this,{H:"div",N:"caption-window",R:{id:"caption-window-"+a.id,dir:k.Oj==T6.yp?"rtl":"ltr",tabindex:0,"aria-live":"assertive",lang:k.lang},L:[{H:"span",N:"captions-text"}]});this.B=[];this.K=!1;this.F=a;this.D=[];this.G=[];this.ua=e;this.sa=f;this.C=null;this.W=.96*e;this.ga=.96*f;this.o=k;this.ra=c;this.A=this.wa["captions-text"];this.ia=null!=this.A.style["box-decoration-break"]||
null!=this.A.style["-webkit-box-decoration-break"];this.M=d/360*16;this.type=U6.vp;this.da=this.M*Sva(l);a=new g.hG(this.element,!0);g.L(this,a);a.subscribe("dragstart",this.YL,this);a.subscribe("dragmove",this.XL,this);a.subscribe("dragend",this.WL,this);this.fa=this.ea=0;a="";this.o.Vj&&(a=O6(this.o.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.o.Vj+")");b={"background-color":a,display:!1===this.o.isVisible?"none":"","text-align":Tva[this.o.textAlign]};this.ia&&(b["border-radius"]=a?this.da/
8+"px":"");g.dh(this.element,b);switch(this.o.Qg){case 0:case 1:case 2:g.R(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.R(this.element,"ytp-caption-window-bottom")}},Sva=function(a){var b=1+.25*(a.Yi||0);
if(a.offset==W6.dv||a.offset==W6.gv)b*=.8;return b},X6=function(a,b){var c={},d=b.background?b.background:a.o.sb.background;
if(null!=b.Ye||b.background){var e=null!=b.Ye?b.Ye:a.o.sb.Ye;d=O6(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.ia&&(c["box-decoration-break"]="clone",c["border-radius"]=a.da/8+"px")}if(null!=b.Yi||null!=b.offset)c["font-size"]=a.M*Sva(b)+"px";d=1;e=b.color||a.o.sb.color;if(b.color||null!=b.Ch)e=O6(e),d=null==b.Ch?a.o.sb.Ch:b.Ch,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=e,c.fill=e;var f=b.Sh;f==g.g3.NONE&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+
d+")";b.Vv&&(k=e=b.Vv);var l=a.M/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),r=Math.max(5*l,1),d=[];switch(f){case g.g3.DROP_SHADOW:for(;q<=r;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case g.g3.RAISED:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case g.g3.DEPRESSED:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case g.g3.ov:for(q=0;5>q;q++)d.push("0 0 "+n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case g.i3.Lu:e=
'"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case g.i3.Qu:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case g.i3.Ku:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case g.i3.CASUAL:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case g.i3.CURSIVE:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case g.i3.zp:e=g.eF()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case g.i3.zu:case g.i3.wp:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.o.sb.offset);switch(e){case W6.dv:c["vertical-align"]="sub";break;case W6.gv:c["vertical-align"]="super"}b.fontFamily==g.i3.zp&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Hr&&(c["font-style"]="italic");b.underline&&
(c["text-decoration"]="underline");b.Vq&&(c.visibility="hidden");return c},Uva=function(a,b,c){a.K=a.K||!!c;
var d={};g.Aa(d,a.o.sb);g.Aa(d,c||b.o);g.Aa(d,a.ra.sb);c=a.D[0];if(c&&d.background==c.background&&d.Ye==c.Ye&&!!d.Vq==!!c.Vq&&d.Sh==c.Sh){var e;for(e=0;e<a.D.length;e++)if(Qva(d,a.D[e])){var f=a.G[e];break}if(!f){e={};for(var k in d)d[k]!=c[k]&&(e[k]=d[k]);f=g.ke("SPAN");g.dh(f,X6(a,e));a.G[0].appendChild(f);e=1}a.G.length=e;a.D.length=e}else a.G.length=0,a.D.length=0,f=g.ke("SPAN"),g.dh(f,X6(a,d)),a.A.appendChild(f);a.C&&a.C.parentNode!=f&&(g.se(a.C),f.appendChild(a.C));c=(k=g.u(b.text))?b.text.split("\n"):
[b.text];for(e=0;e<c.length;e++){var l=c[e];if(0<e||0==a.B.length||!b.C){if(0<e||0!=a.B.length){var m=g.ke("BR");f.appendChild(m)}f.appendChild(g.le("\u00a0"));a.C=g.le("\u00a0");f.appendChild(a.C)}l&&(m=a.C,m.parentNode&&m.parentNode.insertBefore(k?g.le(l):l,m))}a.D.push(d);a.G.push(f);a.B.push(b)},Vva=function(){},Z6=function(a){this.F=a;
this.B=this.o=this.mode=this.A=0;this.C=new Y6(this);this.D=new Y6(this);this.g=[];this.clear()},Xva=function(a,b,c){if(255==a&&255==b||!a&&!b)return{rm:a,
sm:b,result:0};a=Wva[a];b=Wva[b];if(a&128){if(!(b&128)&&0!=c.g&&c.o==b)return{rm:a,sm:b,result:1}}else if(b&128&&1<=a&&31>=a)return{rm:a,sm:b,result:2};return{rm:a,sm:b,result:3}},Zva=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.B&&a.reset(),a.C.g.clear(),a.D.g.clear()):(a.B=0,Yva(a.C,b,c,d))},$va=function(a,b){a.g.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.o=d.time;0==d.type?Zva(a,d.Qv,d.Rv,b):1==d.type&&a.A&496&&Yva(a.D,d.Qv,d.Rv,b)}a.g.length=0},$6=function(){this.g=0},a7=function(){this.o=this.A=this.g=0},b7=function(){this.timestamp=this.xf=0;
this.g=!1},c7=function(a){this.A=[];
for(var b=0;15>=b;b++){this.A[b]=[];for(var c=0;32>=c;c++)this.A[b][c]=new b7}this.g=this.o=this.Oc=0;this.style=new $6;this.C=a;this.B=0},d7=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.C.o+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var r=a.A[m][q];
if(0!=r.xf){0==c&&(c=m,d=q);var n=String.fromCharCode(r.xf),w=r.timestamp;w<e&&(e=w);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==r.xf||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.C.o+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.A[k][m],r=q.xf,0!=r&&(0==c&&(c=k,d=m),n=String.fromCharCode(r),w=q.timestamp,w<=e&&(e=w),l+=n,q.reset()),32==m||0==r)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},ewa=function(a,b){switch(a){case 0:return awa[(b&127)-32];
case 1:return bwa[b&15];case 2:return cwa[b&31];case 3:return dwa[b&31]}return 0},e7=function(a){return a.A[a.Oc][a.o]},f7=function(a,b,c){2<=b&&1<a.o&&(--a.o,e7(a).xf=0);
var d=e7(a);d.timestamp=a.C.o+0;d.xf=ewa(b,c);32>a.o&&a.o++},fwa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.A[b+e][f].Lm(a.A[c+e][f])},g7=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.A[b+d][e].reset()},h7=function(a){a.Oc=0<a.g?a.g:1;
a.o=1;g7(a,0,15)},i7=function(a){this.B=a;
this.C=0;this.style=new $6;this.D=new c7(a);this.F=new c7(a);this.G=new c7(a);this.o=this.D;this.A=this.F;this.g=this.o},j7=function(a,b,c){var d=a.o,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:d7(d,c),h7(a.o),h7(a.A),d.Oc=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.B.mode=1<<d.B;e?d.o=1:d.g!=b&&(d.g>b?(d7(d,c),g7(d,d.Oc-d.g,b)):d.Oc<b&&(b=d.g),d.g=b)},gwa=function(a){a.style.set(1);
a.g=a.A;a.g.g=0;a.g.style=a.style;a.B.mode=1<<a.g.B},hwa=function(a){a.style.set(4);
a.g=a.G;a.g.style=a.style;a.B.mode=1<<a.g.B},Y6=function(a){this.o=a;
this.g=new a7;this.C=0;this.A=new i7(a);this.D=new i7(a);this.B=this.A},Yva=function(a,b,c,d){a.g.update();
b=Xva(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.rm;c=b.sm;if(32<=e||!e)a.o.mode&a.o.A&&(b=e,b&128&&(b=127),c&128&&(c=127),e=a.B.g,b&96&&f7(e,0,b),c&96&&f7(e,0,c),!a.o.F&&0!=b&&0!=c&&3==e.style.g&&d7(e,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.A=e,b.o=c,b.g=2,b=e&8?a.D:a.A,a.B=b,a.o.mode=1<<(a.C<<2)+(b.C<<1)+(4==b.style.g?1:0),(a.o.mode|1<<(a.C<<2)+(b.C<<1)+(4!=b.style.g?1:0))&a.o.A))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&
14)>>1):0;c=b.g;switch(b.style.get()){case 4:d=c.Oc;break;case 3:if(d!=c.Oc){if(d<c.g&&(d=c.g,d==c.Oc))break;var f=1+c.Oc-c.g,k=1+d-c.g;fwa(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));g7(c,b,e)}}c.Oc=d;c.o=a+1}else switch(e&7){case 1:switch(c&112){case 32:f7(b.g,0,32);break a;case 48:57==c?(b=b.g,e7(b).xf=0,32>b.o&&b.o++):f7(b.g,1,c&15)}break;case 2:c&32&&f7(b.g,2,c&31);break;case 3:c&32&&f7(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:gwa(b);break;
case 33:b=b.g;1<b.o&&(--b.o,e7(b).xf=0);break;case 36:b=b.g;d=e7(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.A[a][c]==d){for(;32>=c;c++)b.A[a][c].reset();break}break;case 37:j7(b,2,d);break;case 38:j7(b,3,d);break;case 39:j7(b,4,d);break;case 40:f7(b.g,0,32);break;case 41:b.style.set(2);b.g=b.o;b.g.g=0;b.g.style=b.style;b.B.mode=1<<b.g.B;break;case 42:d=b.G;d.g=15;d.style.set(4);h7(d);hwa(b);break;case 43:hwa(b);break;case 44:a=b.o;switch(b.style.get()){case 1:case 2:case 3:d7(a,d)}g7(a,0,15);break;
case 45:b:{a=b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.Oc){++a.Oc;a.o=1;break b}case 3:}2>a.g&&(a.g=2,a.Oc<a.g&&(a.Oc=a.g));b=a.Oc-a.g+1;d7(a,d);fwa(a,b,b+1,a.g-1);g7(a,a.Oc,1)}break;case 46:g7(b.A,0,15);break;case 47:d7(b.o,d);d=b.A;a=b.B.o+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.A[c][e].timestamp=a;d=b.A;b.A=b.o;b.o=d;gwa(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.g,32<(b.o+=c&3)&&(b.o=32)}}},k7=function(){},l7=function(a){this.A=a;
this.o=null},jwa=function(a,b,c){var d=a.getAttribute("t"),d=d?(0,window.parseInt)(d,10):1E3*(0,window.parseFloat)(a.getAttribute("start")||0),e=a.getAttribute("d"),e=e?(0,window.parseFloat)(e):1E3*(0,window.parseFloat)(a.getAttribute("dur")||0);
b=a.getAttribute("w")||b;var f=!!a.getAttribute("append"),k=f?m7.Ap:m7.Tl;a=g.yr("<html>"+(a.firstChild&&a.firstChild.nodeValue||"")+"</html>");iwa(d,e,k,b,f,a.firstChild,{},c)},iwa=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=!0;
break;case "i":k.Hr=!0;break;case "u":k.underline=!0;break;case "font":var m=f.getAttribute("color");n7.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var n=f.childNodes[m];if(3==n.nodeType)l.push(new P6(a,b,c,d,n.nodeValue,e||0<m,g.Ub(k)?void 0:k));else{var q={};g.Aa(q,k);iwa(a,b,c,d,e||0<m,n,q,l)}}},o7=function(){this.A={};
this.o=null},p7=function(a){this.o={};
this.C={};this.D={};this.A="_"+R6++;this.B=a},q7=function(a,b){var c=a.getAttribute(b);
if(null!=c)return(0,window.parseFloat)(c)},r7=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},s7=function(a,b){var c=q7(a,b);
if(void 0!=c)return c},t7=function(a,b){var c=a.getAttribute(b);
if(null!=c)return n7.test(c),c},kwa=function(a,b){var c={},d=b.getAttribute("ws");
g.Aa(c,d?a.D[d]:a.B);d=s7(b,"mh");null!=d&&(c.Tr=d);d=s7(b,"ju");null!=d&&(c.textAlign=d);d=s7(b,"pd");null!=d&&(c.Oj=d);d=t7(b,"wfc");null!=d&&(c.windowColor=d);d=q7(b,"wfo");void 0!=d&&(c.Vj=d/255);return c},lwa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Aa(c,a.C[d]);d=s7(b,"ap");null!=d&&(c.Qg=d);d=q7(b,"cc");null!=d&&(c.UG=d);d=q7(b,"ah");null!=d&&(c.oi=d);d=q7(b,"rc");null!=d&&(c.uo=d);d=q7(b,"av");null!=d&&(c.Ji=d);return c},mwa=function(a,b,c){var d={};
g.Aa(d,lwa(a,b));g.Aa(d,kwa(a,b));c?Qva(d,a.B)?(c=a.A,d=a.B):c="_"+R6++:c=b.getAttribute("id")||"0";a=q7(b,"t");b=q7(b,"d")||0x8000000000000;return new Q6(a,b,0,c,d)},u7=function(a,b,c){this.F=c;
this.version=this.C=this.D=this.g=0;this.o=new window.DataView(a);this.A=[]},v7=function(a){var b=a.g;
a.g+=1;return a.o.getUint8(b)},nwa=function(a){var b=a.g;
a.g+=4;return a.o.getUint32(b)},w7=function(a,b){this.B=a;
this.o="CC3"==b.D?4:0;this.A=new Z6(!1);this.A.A=1<<this.o},owa=function(a){if(!(a.g<a.o.byteLength))return!1;
var b=nwa(a);b.toString(16);if(1380139777!=b)return!1;a.version=v7(a);if(1<a.version)return!1;v7(a);v7(a);v7(a);return!0},pwa=function(){this.o=[];
this.g=[]},x7=function(a,b){return b?a.g.concat(a.o):a.g},y7=function(a,b){switch(b.B){case "asr":var c=a.o;
g.$a(c,(0,g.y)(b.K,b))||c.push(b);break;default:c=a.g,g.$a(c,(0,g.y)(b.K,b))||c.push(b)}},z7=function(){this.o=null},qwa=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Hr=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType)q=new P6(b,c,d,e.id,q.nodeValue,f||0<n,g.Ub(l)?void 0:l),m.push(q),e!=a.o&&e.o.push(q);else{var r={};g.Aa(r,l);qwa(a,b,c,d,e,!0,q,r,m)}}},A7=function(a){var b=0;
a=g.ia(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+c.value;return 1E3*b},B7=function(a){g.K.call(this);
this.by=!!a;this.o=new pwa;this.C=[];this.g=null},swa=function(a){var b={};
if(a=M6(a))b.lang=a,rwa.test(a)&&(b.Oj=T6.yp);return b},twa=function(a,b,c,d,e){d=d||0;
e=e||0;if(g.u(b)){if("WEBVTT"==b.substring(0,6))return a.g||(a.g=new z7),a.g.g(b,d);b=g.yr(b);if(!b||!b.firstChild)return[];a.g||("timedtext"==b.firstChild.tagName?3==(0,window.parseInt)(b.firstChild.getAttribute("format"),10)?a.g=new p7(swa(c)):a.g=new o7:a.g=new l7(swa(c)));return a.g.g(b,d)}try{if(g.u(b))var f=!1;else{var k=new u7(b,0,0);f=owa(k)}if(f)return a.g||(a.g=new w7(e,c)),a.g.g(b,d)}catch(l){g.FE(l)}return[]},C7=function(a){B7.call(this,a.Am);
this.B=void 0;this.A=null;this.C=a.captionTranslationLanguages},D7=function(){this.rb=[]},E7=function(a,b,c,d,e,f){g.K.call(this);
this.M=a;this.K=b;this.B=new D7;this.g=null;this.D=d;this.J=f;this.o=this.A=null;this.O=c;this.C=e||!1;this.F=new g.Gt(this.vy,1E3,this);g.L(this,this.F);this.G=new g.cG(this);g.L(this,this.G);this.G.T(b,"seekto",this.oz);this.oz(b.getCurrentTime());this.vy()},F7=function(a,b){B7.call(this);
this.D=a;this.U=b;this.A=null;this.B=!1},G7=function(a,b,c,d,e,f){V6.call(this,a,b,c,d,e,f);
this.type=U6.up},H7=function(a,b,c,d,e,f){V6.call(this,a,b,c,d,e,f);
g.R(this.element,"ytp-caption-window-rollup");this.type=U6.xp;this.J=this.O=0;this.P=window.NaN;this.la=null;this.Z=new g.Gt(this.zQ,433,this);g.L(this,this.Z)},I7=function(a){if(!a.O){var b=g.ke("SPAN");
g.dh(b,X6(a,a.o.sb));a.A.appendChild(b);b.appendChild(g.le("M"));var c=b.offsetHeight,d=g.ke("BR");b.appendChild(d);b.appendChild(g.le("M"));a.O=b.offsetHeight-c;a.A.removeChild(b)}return a.O},J7=function(a,b,c,d){B7.call(this,d);
c=c||g.UE(a).hl||"";c=c.split("_").join("-");this.D=g.WE(a,{hl:c});this.B=b;this.F={};this.A=null},N7=function(a){g.$V.call(this,a);
g.fE();this.F=g.W(a);this.o=a.ha();this.ia=g.iV(a);this.U=a;var b=null,c=g.ID("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.wD(c));this.ba=b;this.C={sb:{}};this.G={sb:{}};this.K=[];this.M={};this.W={};this.P=!1;this.la="1"==this.o.Yb.cc_auto_caps||"1"==this.F.O.cc_auto_caps;c=b=this.A=this.B=this.D=this.J=this.O=this.fa=null;K7(this)||(b=new g.Dt(this.sC,void 0,this),g.L(this,b),c=new g.Gt(this.lS,2E3,this),g.L(this,c));this.ea=b;this.ga=c;this.Z=new g.cG(this);g.L(this,this.Z);K7(this)||
this.Z.T(a,"resize",this.It);this.Z.T(a,"onPlaybackAudioChange",this.QN);this.Z.T(a,"crn_captions",this.HL,this);this.Z.T(a,"crx_captions",this.IL,this);L7(this,M7(this,"display-settings")||{});uwa(this)&&this.load()},K7=function(a){if("3"!=a.F.C)return!1;
a=a.U.app.F;return!(!a||!a.g.textTracks)},vwa=function(a){if(a.o.captionTracks.length)var b=a.g.ph().Nv;
if("FORCED_ON"==b||1==a.F.Ug||1==a.o.Ug||"alwayson"==g.WP(a.o,"yt:cc"))return!0;if(2==a.F.Ug){var c=M7(a,"module-enabled");if(null!=c)return!!c}return"ON"==b||"on"==g.WP(a.o,"yt:cc")},uwa=function(a){return K7(a)?!a.o.Aa:a.o.captionTracks.length&&a.g.ph().tk?!0:vwa(a)},wwa=function(a,b){if(a.B){var c=x7(a.B.o,b||a.la);
if(a.D&&a.D.g)return a.D.g;if(!a.F.experiments.g("legacy_default_caption_track"))for(var d=[a.o.Tg,a.F.Tg,g.WP(a.o,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(M6(c[f])==d[e])return c[f];return a.D&&a.D.jq?a.D.jq:c[0]||a.D&&a.D.tk}return null},O7=function(a,b,c,d){a.loaded&&a.unload();
null!=c&&(a.P=c);a.A=b;a.load(d)},xwa=function(a,b){var c=g.GZ(a.ia,!0).height;
if(!c)return null;var d=a.ia.Ya();switch(null!=b.params.Tr?b.params.Tr:b.params.QS?U6.xp:1<b.o.length?U6.up:U6.vp){case U6.up:return new G7(b,a.C,a.G,c,d.width,d.height);case U6.xp:return new H7(b,a.C,a.G,c,d.width,d.height);default:return new V6(b,a.C,a.G,c,d.width,d.height)}},L7=function(a,b,c){var d=P7.sb;
a.C={};g.Aa(a.C,P7);a.C.sb={};g.Aa(a.C.sb,d);a.G={sb:{}};var e=b.backgroundOverride?a.G:a.C,f=b.background||d.background;n7.test(f);e.sb.background=f;e=b.colorOverride?a.G:a.C;f=b.color||d.color;n7.test(f);e.sb.color=f;e=b.windowColorOverride?a.G:a.C;f=b.windowColor||P7.windowColor;n7.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.G:a.C;f=b.backgroundOpacity;null==f&&(f=d.Ye);e.sb.Ye=f;e=b.fontSizeIncrementOverride?a.G:a.C;f=b.fontSizeIncrement;null==f&&(f=d.Yi);e.sb.Yi=f;e=b.textOpacityOverride?
a.G:a.C;f=b.textOpacity;null==f&&(f=d.Ch);e.sb.Ch=f;e=b.windowOpacityOverride?a.G:a.C;f=b.windowOpacity;null==f&&(f=P7.Vj);e.Vj=f;e=b.charEdgeStyleOverride?a.G:a.C;f=b.charEdgeStyle;null==f&&(f=d.Sh);e.sb.Sh=f;e=b.fontFamilyOverride?a.G:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.sb.fontFamily=f;a.loaded&&a.It();c&&Q7(a,"display-settings",b)},zwa=function(a,b){if(b&&!a.J){var c=S6({Oj:T6.tp,
lang:"en"});a.J=[c,new P6(c.start,c.end-c.start,0,c.id,g.T("YTP_SAMPLE_SUBTITLES"))];g.vV(a.g,a.J)}else!b&&a.J&&(ywa(a,a.J),a.J=null)},ywa=function(a,b){g.xV(a.g,b);
(0,g.G)(b,function(a){g.lb(this.K,a)},a);
a.ea.Bk()},Awa=function(a,b){return a&&g.u(a)&&n7.test(a)?a:b},Bwa=function(a,b){return g.oa(a)&&!(0,window.isNaN)(a)?Math.max(0,Math.min(1,(0,window.parseFloat)(a))):b},Dwa=function(a,b){if(a&&g.u(a)){var c=Cwa.indexOf(a);
return-1!=c?c:b}return b},Fwa=function(a,b){if(a&&g.u(a)){var c=Ewa.indexOf(a);
return-1!=c?c:b}return b},Gwa=function(a,b){return g.oa(a)&&!(0,window.isNaN)(a)?g.Kd(a,-2,4):b},M7=function(a,b){if(!a.ba)return null;
try{var c=a.ba.get(b)}catch(d){a.ba.remove(b)}return c},Q7=function(a,b,c){if(a.ba)try{a.ba.set(b,c)}catch(d){}};
g.HJ.prototype.ln=L6(2,function(a){return(a=this.Xh(a))?a.o:0});
g.fM.prototype.ln=L6(1,function(){return 0});
g.EI.prototype.K=L6(0,function(a){return a?this.toString()==a.toString():!1});
var Ova=/^#(?:[0-9a-f]{3}){1,2}$/i,Pva=/#(.)(.)(.)/,rwa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,W6={dv:0,NORMAL:1,gv:2},Ewa="default monoSerif propSerif monoSans propSans casual cursive smallCaps".split(" "),Cwa=["none","raised","depressed","uniform","dropShadow"],n7=/^#(?:[0-9a-f]{3}){1,2}$/i;var R7={Hu:0,J_:1,aE:2},Tva=["left","right","center"],T6={tp:0,yp:1,D0:2,HV:3},m7={Z1:0,Tl:5,Ap:6},U6={vp:0,up:1,xp:2};var P7={windowColor:g.h3.jp,Vj:0,textAlign:R7.aE,Qg:7,oi:50,Ji:100,sb:{background:g.h3.jp,Ye:.75,Sh:g.g3.NONE,color:g.h3.Cp,fontFamily:g.i3.wp,Yi:0,Ch:1,offset:W6.NORMAL}};g.p(P6,g.EJ);P6.prototype.toString=function(){return g.EJ.prototype.toString.call(this)};g.p(Q6,g.EJ);Q6.prototype.toString=function(){return g.EJ.prototype.toString.call(this)};
var R6=0;g.p(V6,g.X);g.h=V6.prototype;g.h.YL=function(a,b){var c=g.th(this.element,this.element.parentElement);this.ea=a-c.x;this.fa=b-c.y;g.R(this.element,"ytp-dragging")};
g.h.XL=function(a,b){var c=g.wh(this.element),d=a-this.ea-.02*this.ua,e=b-this.fa-.02*this.sa,f=(d+c.width/2)/this.W*3,f=Math.floor(g.Kd(f,0,2)),k=(e+c.height/2)/this.ga*3,k=Math.floor(g.Kd(k,0,2)),l=f+3*k,d=(d+f/2*c.width)/this.W,d=100*g.Kd(d,0,1),c=(e+k/2*c.height)/this.ga,c=100*g.Kd(c,0,1);this.F.params.Qg=l;this.F.params.Ji=c;this.F.params.oi=d;this.o.Qg=l;this.o.Ji=c;this.o.oi=d;this.AB()};
g.h.WL=function(){g.Vp(this.element,"ytp-dragging")};
g.h.AB=function(){this.Gi(this.B)};
g.h.Zb=function(){return this.type};
g.h.Gi=function(a){var b=Math.min(this.Ww(),this.W),c=this.Vw();g.dh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"96%",height:c?c+"px":"96%",margin:"",transform:""});this.Op(a);a={transform:"",top:"",left:"",width:b?b+"px":"",height:c?c+"px":""};var d=.96*this.o.oi+2,e=this.o.Qg;switch(e){case 0:case 3:case 6:a.left=d+"%";break;case 1:case 4:case 7:a.left=d+"%";d=this.A.offsetWidth;b||d?(b=b||d+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=
100-d+"%"}b=.96*this.o.Ji+2;switch(e){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.A.offsetHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.dh(this.element,a)};
g.h.Op=function(a){var b;for(b=0;b<a.length&&a[b]==this.B[b];b++);if(this.K||this.B.length>b)b=0,this.K=!1,this.B=[],this.D=[],this.G=[],this.C=null,g.pe(this.A);for(;b<a.length;b++)Uva(this,a[b])};
g.h.Ww=function(){return 0};
g.h.Vw=function(){return 0};
g.h.toString=function(){return g.X.prototype.toString.call(this)};Vva.prototype.B=function(){};Z6.prototype.clear=function(){this.B=this.o=this.mode=0;this.g=[];this.reset()};
Z6.prototype.reset=function(){this.mode=0;this.C.reset(0);this.D.reset(1)};
var Wva=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];$6.prototype.set=function(a){this.g=a};
$6.prototype.get=function(){return this.g};
a7.prototype.clear=function(){this.g=0};
a7.prototype.update=function(){this.g=2==this.g?1:0};
a7.prototype.matches=function(a,b){return 0!=this.g&&a==this.A&&b==this.o};
b7.prototype.Lm=function(a){this.xf=a.xf;this.timestamp=a.timestamp;this.g=a.g};
b7.prototype.reset=function(){this.timestamp=this.xf=0;this.g=!1};
c7.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.A[b][c].reset();this.B=a;this.g=0;this.o=this.Oc=1};
var awa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],bwa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],cwa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],dwa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];i7.prototype.reset=function(a,b){this.C=b;this.style.set(2);this.o=this.D;this.A=this.F;this.g=this.o;var c=(a<<2)+(b<<1)+0;this.D.reset(c);this.F.reset(c);this.G.reset((a<<2)+(b<<1)+1)};
Y6.prototype.reset=function(a){this.C=a;this.g.clear();this.B=this.A;this.A.reset(a,0);this.D.reset(a,1)};k7.prototype.reset=function(){};g.p(l7,k7);l7.prototype.g=function(a){var b=[];this.o||(this.o=S6(this.A),b.push(this.o));a=g.ia(a.firstChild.childNodes);for(var c=a.next();!c.done;c=a.next())jwa(c.value,this.o.id,b);return b};g.p(o7,k7);
o7.prototype.g=function(a){var b=[];this.o||(this.o=S6(),this.A[this.o.id]=this.o,b.push(this.o));for(a=a.firstChild.firstChild;a;){switch(a.tagName){case "window":var c=a,d=c.getAttribute("id");a:{var e=c,f=this.A[d];if(e.getAttribute("t")||e.getAttribute("start")){c=e.getAttribute("start")?1E3*(0,window.parseFloat)(e.getAttribute("start")):(0,window.parseInt)(e.getAttribute("t"),10);f&&(f.end>=c?f.end=c:f=null);switch(e.getAttribute("op")){case "kill":c=null;break a;case "define":f=null}f||(f=S6());
var k={};f&&(g.Aa(k,f.params),f=f.params.sb)&&(k.sb={},g.Aa(k.sb,f));e.getAttribute("rc")&&(k.uo=(0,window.parseInt)(e.getAttribute("rc"),10));e.getAttribute("cc")&&(k.UG=(0,window.parseInt)(e.getAttribute("cc"),10));e.getAttribute("ap")&&(f=(0,window.parseInt)(e.getAttribute("ap"),10),k.Qg=0>f||8<f?7:f);e.getAttribute("ah")&&(k.oi=(0,window.parseInt)(e.getAttribute("ah"),10));e.getAttribute("av")&&(k.Ji=(0,window.parseInt)(e.getAttribute("av"),10));e.getAttribute("vs")&&(k.isVisible=!!e.getAttribute("vs"));
e.getAttribute("ju")&&(k.textAlign=(0,window.parseInt)(e.getAttribute("ju"),10));e.getAttribute("pd")&&(k.Oj=T6.yp,0==(0,window.parseInt)(e.getAttribute("pd"),10)&&(k.Oj=T6.tp));e.getAttribute("bc")&&(k.sb||(k.sb={}),k.sb.backgroundColor=e.getAttribute("bc"));e.getAttribute("bo")&&(k.sb||(k.sb={}),k.sb.Ye=(0,window.parseInt)(e.getAttribute("bo"),10)/100);e.getAttribute("fc")&&(k.sb||(k.sb={}),k.sb.color=e.getAttribute("fc"));e.getAttribute("sd")&&(k.QS=(0,window.parseInt)(e.getAttribute("sd"),10));
f=(0,window.parseInt)(e.getAttribute("d"),10)||1E3*(0,window.parseFloat)(e.getAttribute("dur"))||0x8000000000000;e=e.getAttribute("id")||"0";c=new Q6(c,f,0,e,k)}else c=null}this.A[d]=c;b.push(c);break;case "text":for(d=[],jwa(a,this.o.id,d),d=g.ia(d),c=d.next();!c.done;c=d.next())c=c.value,this.A[c.windowId]&&b.push(c)}a=a.nextSibling}return b};g.p(p7,k7);
p7.prototype.g=function(a){a.firstChild.getAttribute("format");a=g.ia(a.firstChild.childNodes);for(var b=a.next();!b.done;b=a.next())switch(b=b.value,b.tagName){case "head":var c=b;break;case "body":var d=b}if(c)for(c=g.ia(c.childNodes),a=c.next();!a.done;a=c.next())switch(a=a.value,a.tagName){case "pen":var b=a.getAttribute("id"),e=this.o,f={},k=a.getAttribute("p");k&&g.Aa(f,this.o[k]);k=r7(a,"b");null!=k&&(f.bold=k);k=r7(a,"i");null!=k&&(f.Hr=k);k=r7(a,"u");null!=k&&(f.underline=k);k=s7(a,"et");
null!=k&&(f.Sh=k);k=s7(a,"of");null!=k&&(f.offset=k);k=t7(a,"bc");null!=k&&(f.background=k);k=t7(a,"ec");null!=k&&(f.Vv=k);k=t7(a,"fc");null!=k&&(f.color=k);k=s7(a,"fs");void 0!=k&&k!=g.i3.zu&&(f.fontFamily=k);k=q7(a,"sz");void 0!=k&&(f.Yi=k/100-1);k=q7(a,"bo");void 0!=k&&(f.Ye=k/255);a=q7(a,"fo");void 0!=a&&(f.Ch=a/255);e[b]=f;break;case "ws":b=a.getAttribute("id");this.D[b]=kwa(this,a);break;case "wp":b=a.getAttribute("id"),this.C[b]=lwa(this,a)}c=[];if(d){a={};var b=void 0;d=g.ia(d.childNodes);
for(e=d.next();!e.done;e=d.next())switch(e=e.value,e.tagName){case "w":var l=mwa(this,e,!1);(e=a[l.id])&&e.end>l.start&&(e.end=l.start);a[l.id]=l;c.push(l);break;case "p":var m=b,n=Le,f=[],k=e.getAttribute("w")||this.A,q=!!r7(e,"a"),r=q7(e,"t")||0,w=q7(e,"d")||5E3;!n&&!q&&m&&m.windowId==k&&m.end>r&&(m.end=r);for(var m=q?m7.Ap:m7.Tl,n=this.o[e.getAttribute("p")],A=e.childNodes,C=0;C<A.length;C++){var B=A[C];0<C&&(q=!0);if("s"==B.tagName)var N=B,B=r,Y=w,Va=k,nb=q,ka=m,dg=N.textContent?N.textContent:
"",cb=this.o[N.getAttribute("p")],N=q7(N,"t")||0,B=new P6(B+N,Y-N,ka,Va,dg,nb,cb);else B=new P6(r,w,m,k,B.textContent||"",q,n);f.push(B)}b&&"\n"==b.text&&(b.text="");if(0<f.length){b=f[f.length-1];var Le=null!=e.getAttribute("d");f[0].windowId==this.A&&(l=mwa(this,e,!0),c.push(l));e=g.ia(f);for(f=e.next();!f.done;f=e.next())f=f.value,f.windowId=l.id,l.o.push(f),c.push(f)}}}return c};g.p(u7,Vva);u7.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+R6++;c=c/1E3-this.F;d=d/1E3-this.F;var k=m7.Tl;a=new Q6(c,d-c,k,f,{textAlign:R7.Hu,Qg:0,oi:2.5*b,Ji:5.33*a});e=new P6(c,d-c,k,f,e);this.A.push(a);this.A.push(e)}};
g.p(w7,k7);w7.prototype.g=function(a){a=new u7(a,0,this.B);if(owa(a)){for(;a.g<a.o.byteLength;)for(0==a.version&&(a.D=nwa(a)*(1E3/45)),a.C=v7(a);0<a.C;a.C--){var b=v7(a),c=v7(a),d=v7(a);b&4&&(b&3)==this.o&&(0==this.o||1==this.o)&&(b=this.A,b.g.push({time:a.D,type:this.o,Qv:c,Rv:d,order:b.g.length}))}$va(this.A,a);return a.A}return[]};
w7.prototype.reset=function(){this.A.clear()};g.p(z7,k7);
z7.prototype.g=function(a,b){for(var c=[],d=a.split(Hwa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!Iwa.test(f)){var l=S7.exec(f);if(l&&3<=l.length){var m=A7(l[1]),l=A7(l[2])-m,m=m+k,f=f.substring(S7.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");S7.lastIndex=0;var n=f,f={};this.o||(this.o=S6({Tr:U6.vp}),c.push(this.o));var q=this.o,k=m7.Tl;if(0>n.indexOf("<"))c.push(new P6(m,l,k,q.id,n,!1,g.Ub(f)?void 0:f));else{n=n.split(Jwa);1!=n.length&&(k=m7.Ap,q="_"+Kwa++,q=new Q6(m,l,k,q,{}),c.push(q));
for(var r=m,w=0;w<n.length;w++){var A=n[w];if(0==w%2){var C=g.yr("<html>"+A+"</html>");if(C.getElementsByTagName("parsererror").length){var B=C.createElement("span");B.appendChild(C.createTextNode(A))}else B=C.firstChild;qwa(this,r,l-(r-m),k,q,0<w,B,f,c)}else r=A7(A)}}}S7.lastIndex=0}}return c};
var Kwa=0,Iwa=/^NOTE/,Hwa=/(?:\r\n|\r|\n){2,}/,S7=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3}).*(?:\r\n|\r|\n)","gm"),Jwa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.p(B7,g.K);B7.prototype.Jd=function(){this.g=null};
B7.prototype.X=function(){g.K.prototype.X.call(this);this.Jd()};
B7.prototype.lB=function(){return!1};g.p(C7,B7);g.h=C7.prototype;g.h.Nr=function(a,b){var c=this.zk(a),d=(0,g.y)(function(c){this.A=null;b(c.responseText,a)},this);
this.Jd();this.A=g.$E(c,{format:"RAW",Lb:d,withCredentials:!0})};
g.h.Or=function(a,b,c,d){this.B=c;if(d)for(b=g.ia(d.captionTracks),c=b.next();!c.done;c=b.next())y7(this.o,c.value);a()};
g.h.zk=function(a){var b=a.J,c={};if(this.B||a.A)c.fmt=this.B||"srv"+a.A;a.g&&(c.tlang=a.g.languageCode);return g.WE(b,c)};
g.h.Jd=function(){B7.prototype.Jd.call(this);this.A&&this.A.abort()};
g.h.X=function(){this.Jd();B7.prototype.X.call(this)};D7.prototype.contains=function(a){a=g.xb(this.rb,a);return 0<=a||0>a&&1==(-a-1)%2};
D7.prototype.length=function(){return this.rb.length/2};g.p(E7,g.K);g.h=E7.prototype;g.h.X=function(){g.K.prototype.X.call(this);this.o&&this.o.abort()};
g.h.oz=function(a){var b=this.g;this.g=g.Ya(this.O.ah(a).g);b!=this.g&&this.J&&this.J()};
g.h.reset=function(){this.B=new D7;this.o&&(this.o.abort(),this.o=null)};
g.h.vy=function(){var a;if(a=null!==this.g)a=this.g,a=a.na.yi(a);if(a&&!this.o&&!(this.g&&30<this.g.startTime-this.K.getCurrentTime())){a=this.g;a=a.na.Xk(a);if(!this.B.contains(a.g[0].Ba)){var b=g.NL(g.RL(a,this.M,{})),c={format:"RAW",Hd:(0,g.y)(this.vQ,this),withCredentials:!0};this.C&&(c.responseType="arraybuffer");this.o=g.$E(b,c);this.A=a;var b=this.B,c=this.A.g[0].Ba,d=g.xb(b.rb,c);0<=d||0>d&&1==(-d-1)%2||(d=-d-1,0<d&&1==c-b.rb[d-1]&&d<b.rb.length&&1==b.rb[d]-c?(g.jb(b.rb,d),g.jb(b.rb,d-1)):
0<d&&1==c-b.rb[d-1]?b.rb[d-1]=c:d<b.rb.length&&1==b.rb[d]-c?b.rb[d]=c:(g.tb(b.rb,d,0,c),g.tb(b.rb,d+1,0,c)))}this.g=g.Ya(a.g)}this.F.start()};
g.h.vQ=function(a){(this.C?!a.response:!a.responseText)||400<=a.status||null===this.D||(this.C?this.D(a.response,1E3*this.A.g[0].startTime):this.D(a.responseText,1E3*this.A.g[0].startTime));this.o=this.A=null};g.p(F7,B7);g.h=F7.prototype;g.h.Nr=function(a,b){this.Jd();var c=this.D.g[a.o];if(c){var d=1E3*c.index.ln(c.index.ug()),e=g.W(this.U).xd;this.A=new E7(new g.RK,this.U,c,function(c,e){b(c,a,e,d)},e,(0,g.y)(function(){e&&(this.A&&this.A.reset(),this.g&&this.g.reset(),this.B=!0)},this))}};
g.h.lB=function(){var a=this.B;this.B=!1;return a};
g.h.Or=function(a){g.W(this.U).xd?(y7(this.o,new g.EI({format:1,languageCode:"rawcc",languageName:"CC1",name:"",is_servable:!0,is_default:!0,is_translateable:!1})),y7(this.o,new g.EI({format:1,languageCode:"rawcc",languageName:"CC3",name:"",is_servable:!0,is_default:!0,is_translateable:!1}))):y7(this.o,new g.EI({format:1,languageCode:"en",languageName:"English",name:"",is_servable:!0,is_default:!0,is_translateable:!1}));a()};
g.h.Jd=function(){B7.prototype.Jd.call(this);this.A&&(this.A.dispose(),this.A=null)};
g.h.zk=function(){return""};
g.h.X=function(){this.Jd();B7.prototype.X.call(this)};g.p(G7,V6);G7.prototype.Op=function(a){var b=this.F.o;V6.prototype.Op.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.o==e)var d=f;else{d={};g.Aa(d,c.o);g.Aa(d,Lwa);var e=c.o;var f=d}Uva(this,c,d)}};
var Lwa={Vq:!0};g.p(H7,V6);g.h=H7.prototype;g.h.AB=function(){g.Ht(this.Z)};
g.h.zQ=function(){g.Vp(this.element,"ytp-rollup-mode");this.Gi(this.la,!0)};
g.h.Ww=function(){return this.J};
g.h.Vw=function(){return this.F.params.uo*I7(this)};
g.h.Gi=function(a,b){this.la=a;if(I7(this)){for(var c=0,d=0;d<this.B.length&&c<a.length;d++)this.B[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.B.concat(a.slice(c)));c=this.J;this.J=0;V6.prototype.Gi.call(this,a);this.J=Math.max(c,this.A.offsetWidth+1);c=this.F.params.uo*I7(this)-this.A.offsetHeight;c!=this.P&&(b||(0,window.isNaN)(this.P)||(g.R(this.element,"ytp-rollup-mode"),this.Z.Qd()),g.dh(this.A,"transform",c?"translateY("+c+"px)":""),this.P=c);V6.prototype.Gi.call(this,a)}else V6.prototype.Gi.call(this,
a)};g.p(J7,B7);g.h=J7.prototype;g.h.Nr=function(a,b){var c=this.zk(a),d=(0,g.y)(function(c){this.A=null;b(c.responseText,a)},this);
this.Jd();this.A=g.$E(c,{format:"RAW",Lb:d,withCredentials:!0})};
g.h.Or=function(a,b,c){var d=this.D;b={type:"list",tlangs:1,v:this.B,fmts:Number(b||!1),vssids:1};this.by&&(b.asrs=1);d=g.WE(d,b);b=(0,g.y)(function(b){this.A=null;if((b=b.responseXML)&&b.firstChild){for(var d=this.o,e=g.ia(b.getElementsByTagName("track")),l=e.next();!l.done;l=e.next()){var m=l.value,l=m.getAttribute("formats"),n=m.getAttribute("lang_code"),q=m.getAttribute("lang_translated"),r=m.getAttribute("name"),w=m.getAttribute("kind"),A=m.getAttribute("id"),C="true"==m.getAttribute("cantran"),
m=m.getAttribute("vss_id");y7(d,new g.EI({formats:l,format:c,languageCode:n,languageName:q,name:r,kind:w,id:A,is_servable:!0,is_translateable:C,vss_id:m}))}b=b.getElementsByTagName("target");d=b.length;for(e=0;e<d;e++)l=b[e].getAttribute("lang_code"),n=b[e].getAttribute("lang_translated"),q=b[e].getAttribute("lang_original"),r=b[e].getAttribute("id"),l={languageCode:l,languageName:n,languageOriginal:q,id:r},this.F[l.languageCode]=l.languageName,this.C.push(new g.DI(l))}a()},this);
this.Jd();this.A=g.$E(d,{format:"RAW",Lb:b,withCredentials:!0})};
g.h.zk=function(a){var b=this.D,c={v:this.B,type:"track",lang:a.o,name:a.C,kind:a.B,fmt:a.A};a.g&&(c.tlang=M6(a));return b=g.WE(b,c)};
g.h.Jd=function(){B7.prototype.Jd.call(this);this.A&&this.A.abort()};
g.h.X=function(){this.Jd();B7.prototype.X.call(this)};g.p(N7,g.$V);g.h=N7.prototype;g.h.X=function(){K7(this)||zwa(this,!1);g.$V.prototype.X.call(this)};
g.h.load=function(a){g.$V.prototype.load.call(this);this.D=this.g.ph();if(this.B||a)this.A?(a?this.UA(a,this.A):3!=this.g.Xa()&&this.B.Nr(this.A,(0,g.y)(this.UA,this)),this.g.ya("captionschanged",N6(this.A))):this.g.ya("onCaptionsTrackListChanged");else{var b;a=this.o;a.Aa||g.W(this.U).xd&&null!=a.va&&null!=a.va.g.rawcc?b=new F7(this.o.va,this.g):this.o.captionTracks.length?b=new C7(this.o):b=new J7(this.o.Bm,this.o.videoId,this.o.Tg||this.F.Tg||g.WP(this.o,"yt:cc_default_lang")||this.F.Ka,this.o.Am);
this.B=b;b.Or((0,g.y)(this.cR,this),!0,K7(this)?"vtt":void 0,this.g.ph())}};
g.h.unload=function(){if(K7(this))for(var a=g.Yd(window.document,"track",void 0,this.U.app.F.g),b=0;b<a.length;b++)g.se(a[b]);else g.It(this.ga),g.yV(this.g,"captions"),this.K=[],this.B&&this.B.Jd(),this.J&&g.vV(this.g,this.J),this.It();g.$V.prototype.unload.call(this);(a=g.gV(this.g.app))&&a.D&&g.jQ(a.D.A);this.g.ya("captionschanged",{})};
g.h.cR=function(){if(this.P||vwa(this))var a=wwa(this,this.P);if(K7(this))for(var b=x7(this.B.o,!0),c=0;c<b.length;c++){var d=b[c],e={kind:"subtitles",label:g.FI(d),srclang:M6(d),src:this.B.zk(d)};d==a&&(e["default"]=1);for(var d=this.U.app.F,e=[g.ie("TRACK",e)],f=0;f<e.length;f++)d.g.appendChild(e[f])}else!this.A&&a&&O7(this,a),this.g.ya("onCaptionsTrackListChanged"),this.g.ya("onApiChange")};
g.h.fT=function(){this.loaded&&!K7(this)&&this.unload()};
g.h.UA=function(a,b,c,d){if(a){this.B.lB()&&(this.K=[],g.yV(this.U,"captions"),this.ea.Bk());a=twa(this.B,a,b,c,d);c={trackName:b.C,trackKind:b.B,trackLangCode:M6(b)};b.g&&(c.fromLangCode=b.o);g.pV(this.g,"cc",c);if(this.A!=(this.D&&this.D.tk)){if(this.P&&!g.TN(this.F)&&!g.UN(this.F)){g.It(this.ga);b=S6({Qg:0,oi:5,Ji:5,uo:2,textAlign:R7.Hu,Oj:T6.tp,lang:"en"});this.O=[b];c=g.T("YTP_CLICK_FOR_SETTINGS").split("$GEAR_ICON");this.fa||(d=new g.JV(g.yE()),g.L(this,d),this.fa=d.element);d=b.end-b.start;
var e=g.FI(this.A);e&&this.O.push(new P6(b.start,d,0,b.id,e));this.O.push(new P6(b.start,d,0,b.id,c[0]),new P6(b.start,d,0,b.id,this.fa,!0),new P6(b.start,d,0,b.id,c[1],!0));g.vV(this.g,this.O);this.ga.Qd()}if(this.P||g.TN(this.F))Q7(this,"module-enabled",!0),this.D&&(this.D.g=this.A);(b=g.gV(this.g.app))&&b.D&&g.jQ(b.D.A)}g.vV(this.g,a);this.P=!1}};
g.h.HL=function(a){this.K.push(a);this.ea.Bk()};
g.h.IL=function(a){g.lb(this.K,a);this.ea.Bk()};
g.h.WR=function(a){if(a instanceof Q6){var b=this.M[a.id];b&&b.F!=a&&(b.dispose(),delete this.M[a.id],b=null);b||(b=xwa(this,a))&&(this.M[a.id]=b)}else b=a.windowId,this.W[b]||(this.W[b]=[]),this.W[b].push(a)};
g.h.lS=function(){ywa(this,this.O);this.O=null};
g.h.sC=function(){this.ea.stop();Rva(this.W);this.K.sort(g.FJ);var a=this.K;if(this.J){var b=(0,g.ue)(a,function(a){return-1==this.J.indexOf(a)},this);
b.length&&(a=b)}(0,g.G)(a,this.WR,this);g.Jb(this.M,function(a,b){this.W[b]?(a.element.parentNode||g.CV(this.g,a.element,4),a.Gi(this.W[b])):(a.dispose(),delete this.M[b])},this)};
g.h.zB=function(){L7(this,{},!0)};
g.h.Dq=function(){var a=P7.sb,a={background:a.background,backgroundOpacity:a.Ye,charEdgeStyle:a.Sh,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.Yi,textOpacity:a.Ch,windowColor:P7.windowColor,windowOpacity:P7.Vj},b=M7(this,"display-settings"),c;for(c in b)null!=b[c]&&(a[c]=b[c]);return a};
g.h.Lt=function(a,b){var c={};g.Aa(c,M7(this,"display-settings"));g.Aa(c,a);L7(this,c,b);this.g.Y("captionssettingschanged")};
g.h.It=function(){!K7(this)&&this.loaded&&(g.Jb(this.M,function(a,b){a.dispose();delete this.M[b]},this),this.sC())};
g.h.ks=function(a,b){switch(a){case "fontSize":if((0,window.isNaN)(b))break;var c=g.Kd(b,-2,4);this.Lt({fontSizeIncrement:c});return c;case "reload":b&&!K7(this)&&O7(this,this.A,!0);break;case "stickyLoading":void 0!=b&&this.F.Gb&&Q7(this,"module-enabled",!!b);break;case "track":if(!this.B)return{};if(b){if(K7(this))break;if(!g.wa(b))break;if(g.Ub(b)){O7(this,null,!0);break}for(var d=x7(this.B.o,!0),e=0;e<d.length;e++){var f=d[e];f.o!=b.languageCode||c&&f.D!=b.languageName||(c=b.translationLanguage?
Nva(f,b.translationLanguage):f)}!c||c==this.A&&this.loaded||O7(this,c,!0)}else return this.loaded&&this.A&&this.A!=(this.D&&this.D.tk)?N6(this.A):{};return"";case "tracklist":return this.B?(0,g.H)(x7(this.B.o,b&&b.includeAsr),function(a){return N6(a)}):[];
case "translationLanguages":return this.B?this.B.C:[];case "displaySettings":c=this.Dq();if(g.TN(this.F)&&b&&g.wa(b))if(b.reset)this.zB();else{f={};for(d in b)switch(d){case "color":case "background":case "windowColor":f[d]=Awa(b[d],c[d]);break;case "textOpacity":case "backgroundOpacity":case "windowOpacity":f[d]=Bwa(b[d],c[d]);break;case "charEdgeStyle":f[d]=Dwa(b[d],c[d]);break;case "fontSizeIncrement":f[d]=Gwa(b[d],c[d]);break;case "fontFamilyOption":f.fontFamily=Fwa(b[d],c[d])}for(e in f)f[e+
"Override"]=!0;this.Lt(f,!0);c=this.Dq()}c.fontFamilyOption=Ewa[c.fontFamily];c.charEdgeStyle=Cwa[c.charEdgeStyle];return c;case "sampleSubtitles":K7(this)||void 0==b||zwa(this,!!b);break;case "xmlTrack":b&&this.F.Gb&&(K7(this)||O7(this,new g.EI({languageName:b.name}),!1,b.xml))}};
g.h.FL=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.F.Gb&&a.push("stickyLoading","xmlTrack");return a};
g.h.GL=function(){var a=this.A;return a?{cc:a.F}:{}};
g.h.qC=function(){this.loaded&&this.A?(Q7(this,"module-enabled",!1),this.unload()):O7(this,this.A||wwa(this,!0),!0)};
g.h.QN=function(){this.o.captionTracks.length&&(this.loaded&&this.unload(),uwa(this)&&this.load())};g.rW("captions",N7);})(_yt_player);
