# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  cloudinary_cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  cloudinary_api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  cloudinary_api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
  secret_key_base: 95713d79c39bf6c0eb1361b0974b61ddd6b6883bf7c796d776278a7b5874495a6bf6e2c844a3c372226494cc9a846de3907fe010245b9d110096be0644aa2ffd

test:
  cloudinary_cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  cloudinary_api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  cloudinary_api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
  secret_key_base: e0b92acdc25652ed2bbeb774a360ce94fa63857fc293fb39e6b2a473738c9f1aa85ab52768bac2051b6e1c8b994d86ec3f836af1c118ba0a8a21ff02fe8d86d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  cloudinary_cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  cloudinary_api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  cloudinary_api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
